server:
  port: ${port:10086}
spring:
  application:
    name: eureka-server # 应用名称，作为serviceId
eureka:
  client:
    service-url: # EkServer的地址，现在是自己的地址，集群状态写其他
      defaultZone: ${defaultZone:http://127.0.0.1:10086/eureka}
    register-with-eureka: true # 集群环境注册自己
    fetch-registry: true # 集群环境拉取服务